# Generated by Django 5.2.1 on 2025-06-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_remove_task_complete_remove_task_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task',
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
